spring.application.name=api-gateway
server.port=8083

spring.cloud.gateway.server.webmvc.routes[0].id=greet-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/greet/**